from django.urls import path

from .views import (
    SurveyByTokenView,
    customer_create,
    customer_detail,
    customer_delete,
    customer_edit,
    customer_list,
    question_create,
    question_detail,
    question_delete,
    question_edit,
    question_list,
    survey_assignment_portal,
    survey_snapshot_csv,
    survey_session_detail,
    survey_link_toggle,
    survey_session_delete,
    survey_saved,
    survey_thanks,
    user_create,
    user_delete,
    user_edit,
    user_list,
    template_builder,
    template_preview,
    template_builder_data,
    template_copy,
    template_create,
    template_delete,
    template_demo,
    template_demo_done,
    template_edit,
    template_list,
    template_node_create,
    template_node_delete,
    template_node_update,
    template_check_errors,
    template_save_ready,
)

urlpatterns = [
    path("management/users/", user_list, name="management-users"),
    path("management/users/new/", user_create, name="management-user-create"),
    path("management/users/<int:user_id>/edit/", user_edit, name="management-user-edit"),
    path("management/users/<int:user_id>/delete/", user_delete, name="management-user-delete"),
    path("management/customers/", customer_list, name="management-customers"),
    path("management/customers/<int:customer_id>/", customer_detail, name="management-customer-detail"),
    path("management/customers/new/", customer_create, name="management-customer-create"),
    path("management/customers/<int:customer_id>/edit/", customer_edit, name="management-customer-edit"),
    path("management/customers/<int:customer_id>/delete/", customer_delete, name="management-customer-delete"),
    path("management/assignments/", survey_assignment_portal, name="management-assignments"),
    path("management/assignments/<int:session_id>/", survey_session_detail, name="management-assignment-detail"),
    path(
        "management/assignments/<int:session_id>/snapshots/<int:snapshot_id>/csv/",
        survey_snapshot_csv,
        name="management-assignment-snapshot-csv",
    ),
    path("management/assignments/<int:session_id>/link-toggle/", survey_link_toggle, name="management-assignment-link-toggle"),
    path("management/assignments/<int:session_id>/delete/", survey_session_delete, name="management-assignment-delete"),
    path("management/questions/", question_list, name="management-questions"),
    path("management/questions/new/", question_create, name="management-question-create"),
    path("management/questions/<int:question_id>/", question_detail, name="management-question-detail"),
    path("management/questions/<int:question_id>/edit/", question_edit, name="management-question-edit"),
    path("management/questions/<int:question_id>/delete/", question_delete, name="management-question-delete"),
    path("management/templates/", template_list, name="management-templates"),
    path("management/templates/copy/", template_copy, name="management-template-copy"),
    path("management/templates/new/", template_create, name="management-template-create"),
    path("management/templates/<int:template_id>/edit/", template_edit, name="management-template-edit"),
    path("management/templates/<int:template_id>/delete/", template_delete, name="management-template-delete"),
    path("management/templates/<int:template_id>/builder/", template_builder, name="management-template-builder"),
    path("management/templates/<int:template_id>/preview/", template_preview, name="management-template-preview"),
    path("management/templates/<int:template_id>/demo/", template_demo, name="management-template-demo"),
    path("management/templates/<int:template_id>/demo/done/", template_demo_done, name="management-template-demo-done"),
    path("management/templates/<int:template_id>/builder/data/", template_builder_data, name="management-template-builder-data"),
    path("management/templates/<int:template_id>/builder/nodes/create/", template_node_create, name="management-template-node-create"),
    path(
        "management/templates/<int:template_id>/builder/nodes/<int:node_id>/update/",
        template_node_update,
        name="management-template-node-update",
    ),
    path(
        "management/templates/<int:template_id>/builder/nodes/<int:node_id>/delete/",
        template_node_delete,
        name="management-template-node-delete",
    ),
    path(
        "management/templates/<int:template_id>/save-ready/",
        template_save_ready,
        name="management-template-save-ready",
    ),
    path(
        "management/templates/<int:template_id>/check-errors/",
        template_check_errors,
        name="management-template-check-errors",
    ),
    path("s/<uuid:token>/", SurveyByTokenView.as_view(), name="survey-by-token"),
    path("s/<uuid:token>/saved/", survey_saved, name="survey-saved"),
    path("s/<uuid:token>/thanks/", survey_thanks, name="survey-thanks"),
]
