# Generated by Django 5.2.7 on 2026-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcandidate',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='leadcandidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
