# Generated by Django 5.2.7 on 2026-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_leadcandidate_address_leadcandidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcandidate',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
