# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_leadcandidate_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadcandidate",
            name="nip",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
