# Generated by Django 6.0.2 on 2026-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatenode',
            name='close_on_no',
        ),
        migrations.AddField(
            model_name='templatenode',
            name='end_on_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatenode',
            name='end_on_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatenode',
            name='ends_survey',
            field=models.BooleanField(default=False),
        ),
    ]
