# Generated by Django 6.0.2 on 2026-02-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_templatenode_close_on_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=20),
        ),
    ]
