# Generated by Django 6.0.2 on 2026-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='first_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='last_reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='last_saved_again_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='saved_again_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('saved_again', 'Saved Again')], db_index=True, default='open', max_length=20),
        ),
    ]
