# Generated by Django 6.0.2 on 2026-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveysession_first_saved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='is_link_active',
            field=models.BooleanField(default=True),
        ),
    ]
