# Generated by Django 6.0.2 on 2026-02-28 18:10

from django.db import migrations, models


SYSTEM_START_QUESTION_TITLE = "Imie i nazwisko osoby wypelniajacej ankiete"
SYSTEM_START_QUESTION_HELP = "Podaj imie i nazwisko."


def create_forced_start_nodes(apps, schema_editor):
    Question = apps.get_model("surveys", "Question")
    SurveyTemplate = apps.get_model("surveys", "SurveyTemplate")
    TemplateNode = apps.get_model("surveys", "TemplateNode")

    system_question = Question.objects.filter(is_system=True).order_by("id").first()
    if system_question is None:
        system_question = Question.objects.create(
            title=SYSTEM_START_QUESTION_TITLE,
            question_type="open",
            help_text=SYSTEM_START_QUESTION_HELP,
            required=True,
            is_system=True,
        )
    else:
        system_question.title = SYSTEM_START_QUESTION_TITLE
        system_question.question_type = "open"
        system_question.help_text = SYSTEM_START_QUESTION_HELP
        system_question.required = True
        system_question.is_system = True
        system_question.save(update_fields=["title", "question_type", "help_text", "required", "is_system", "updated_at"])

    for template in SurveyTemplate.objects.all().order_by("id"):
        previous_start_id = template.start_node_id
        forced_node = TemplateNode.objects.filter(template_id=template.id, is_forced_start=True).order_by("id").first()

        if forced_node is None:
            forced_node = TemplateNode.objects.create(
                template_id=template.id,
                question_id=system_question.id,
                is_forced_start=True,
                x=60,
                y=30,
                next_node_id=previous_start_id if previous_start_id else None,
            )
        else:
            update_fields = []
            if forced_node.question_id != system_question.id:
                forced_node.question_id = system_question.id
                update_fields.append("question")
            if not forced_node.is_forced_start:
                forced_node.is_forced_start = True
                update_fields.append("is_forced_start")
            if forced_node.ends_survey:
                forced_node.ends_survey = False
                update_fields.append("ends_survey")
            if forced_node.end_on_yes:
                forced_node.end_on_yes = False
                update_fields.append("end_on_yes")
            if forced_node.end_on_no:
                forced_node.end_on_no = False
                update_fields.append("end_on_no")
            if forced_node.yes_node_id is not None:
                forced_node.yes_node_id = None
                update_fields.append("yes_node")
            if forced_node.no_node_id is not None:
                forced_node.no_node_id = None
                update_fields.append("no_node")
            if forced_node.next_node_id is None and previous_start_id and previous_start_id != forced_node.id:
                forced_node.next_node_id = previous_start_id
                update_fields.append("next_node")
            if update_fields:
                forced_node.save(update_fields=update_fields)

        if template.start_node_id != forced_node.id:
            template.start_node_id = forced_node.id
            template.save(update_fields=["start_node", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0006_surveysession_is_link_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templatenode",
            name="is_forced_start",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_forced_start_nodes, migrations.RunPython.noop),
    ]
