# Generated by Django 6.0.2 on 2026-02-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_question_is_system_templatenode_is_forced_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('answers', models.JSONField(default=list)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='surveys.surveysession')),
            ],
            options={
                'ordering': ['-version_number', '-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'version_number'), name='unique_snapshot_version_per_session')],
            },
        ),
    ]
