# Generated by Django 6.0.2 on 2026-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveysubmissionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
