# Generated by Django 6.0.2 on 2026-03-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_customer_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
