# Generated by Django 6.0.2 on 2026-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_force_questions_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complex_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='complex_answer',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('multi_choice', 'Multi choice'), ('open', 'Open question'), ('complex', 'Complex')], max_length=20),
        ),
    ]
