# Generated by Django 6.0.2 on 2026-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_question_complex_items_surveyanswer_complex_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='promotional_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
