# Generated by Django 6.0.2 on 2026-03-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_question_promotional_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='first_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SurveySessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('link_opened', 'Link opened'), ('question_viewed', 'Question viewed'), ('answer_saved', 'Answer saved'), ('survey_submitted', 'Survey submitted'), ('survey_reopened', 'Survey reopened')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='surveys.templatenode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='surveys.surveysession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
