# Generated by Django 6.0.2 on 2026-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_customer_archived_at_customer_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
