# Generated by Django 6.0.2 on 2026-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_surveysession_created_by_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSurveySession',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Survey',
                'verbose_name_plural': 'Archived Surveys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.surveysession',),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
