# Generated by Django 6.0.2 on 2026-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_surveysession_consent_contact_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysession",
            name="is_internal",
            field=models.BooleanField(default=False),
        ),
    ]
