# Generated by Django 6.0.2 on 2026-03-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_surveysession_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('yes_no_next', 'Yes / No (no condition)'), ('multi_choice', 'Multi choice'), ('open', 'Open question'), ('complex', 'Complex')], max_length=20),
        ),
    ]
