# Generated by Codex on 2026-05-18

from django.db import migrations, models


def backfill_rodo_clause(apps, schema_editor):
    SurveySession = apps.get_model("surveys", "SurveySession")
    SurveySession.objects.filter(
        consent_personal_data=True,
        consent_data_administration=True,
        consent_contact_results=True,
    ).update(consent_rodo_clause=True)


def reverse_backfill_rodo_clause(apps, schema_editor):
    SurveySession = apps.get_model("surveys", "SurveySession")
    SurveySession.objects.update(consent_rodo_clause=False)


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0028_move_customer_to_crm"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysession",
            name="consent_rodo_clause",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_rodo_clause, reverse_backfill_rodo_clause),
    ]
