# Generated by Django 5.2.7 on 2026-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_surveysession_consent_rodo_clause'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedsurveysession',
            options={'verbose_name': 'Archiwalna ankieta', 'verbose_name_plural': 'Archiwalne ankiety'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_finishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='finishing_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templatenode',
            name='is_finishing_injected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Tak / Nie'), ('yes_no_next', 'Tak / Nie (bez warunku)'), ('multi_choice', 'Multi-wiele'), ('multi_one', 'Multi-jeden'), ('open_with_list', 'Adress List'), ('open_number_list', 'Checkbox/Number'), ('open_numeric', 'Numeric'), ('open', 'Pytanie otwarte'), ('complex', 'Complex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarta'), ('closed', 'Zamknięta'), ('reopened', 'Otwarta ponownie'), ('saved_again', 'Zapisana ponownie')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveysessionevent',
            name='event_type',
            field=models.CharField(choices=[('link_opened', 'Otwarcie linku'), ('question_viewed', 'WyÅ\x9bwietlenie pytania'), ('answer_saved', 'Zapis odpowiedzi'), ('survey_submitted', 'Zapisanie ankiety'), ('survey_reopened', 'Ponowne otwarcie ankiety')], max_length=30),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('ready', 'Gotowy')], default='draft', max_length=20),
        ),
    ]
