# Generated by Django 5.2.7 on 2026-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
