# Generated by Codex on 2026-05-18

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_customer_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="nip",
            field=models.CharField(blank=True, db_index=True, max_length=10, validators=[crm.models.validate_nip]),
        ),
    ]
